Add job for publishing images to github registry
Signed-off-by: Patrik Stas <patrik.stas@gmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -421,3 +421,48 @@ jobs:
       - name: Verify image was loaded
         run: |
           docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_DAEMON_UI" || { echo "Image $DOCKER_IMG_NAME_DAEMON_UI was not found!" ; exit 1; }
+
+  public-docker-api:
+    runs-on: ubuntu-16.04
+    needs: [workflow-setup, build-docker-api]
+    env:
+      CACHE_KEY_API: ${{ needs.workflow-setup.outputs.CACHE_KEY_API }}
+      DOCKER_IMG_NAME_API: ${{ needs.workflow-setup.outputs.DOCKER_IMG_NAME_API }}
+      PUBLISH_VERSION: ${{needs.workflow-setup.outputs.PUBLISH_VERSION}}
+    steps:
+      - name: Git checkout
+        uses: actions/checkout@v2
+      - name: Load image cache
+        id: load-cached-image
+        uses: actions/cache@v2
+        with:
+          path: /tmp/docker
+          key: ${{ env.CACHE_KEY_API }}
+      - name: If no cached image found
+        if: steps.load-cached-image.outputs.cache-hit != 'true'
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_API"; exit -1
+      - name: Load image from cache
+        run: docker load < /tmp/docker/img.rar
+      - name: Verify libvcx image were loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_API" || { echo "Image $DOCKER_IMG_NAME_API was not found!" ; exit 1; }
+      - name: Docker Login
+        uses: azure/docker-login@v1
+        with:
+          login-server: docker.pkg.github.com
+          username: $GITHUB_ACTOR
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Publish image
+        run: |
+          if [[ "$PUBLISH_VERSION" ]]
+          then
+            IFS=$':' read -a arr <<< $DOCKER_IMG_NAME_API
+            DOCKER_IMG_NAME_TAGLESS=${arr[0]}
+            GITHUB_REPOSITORY_LOWERCASE=`echo $GITHUB_REPOSITORY | awk '{print tolower($0)}'`
+            REMOTE_DOCKER_IMG_NAME="docker.pkg.github.com/${GITHUB_REPOSITORY_LOWERCASE}/${DOCKER_IMG_NAME_TAGLESS}:${PUBLISH_VERSION}"
+            echo "Publishing image $REMOTE_DOCKER_IMG_NAME"
+            docker tag "$DOCKER_IMG_NAME_API" "$REMOTE_DOCKER_IMG_NAME"
+            docker push "$REMOTE_DOCKER_IMG_NAME" || true
+          else
+             echo "New version was not defined, skipping release."
+          fi
